### ISSUE TITLE
Support IxDyn/vec![] dimension better

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#10]
- [ ] mutate in place stepping for the iterator
- [x] Pass index as slice
- [x] allow indexing with regular arrays (#225)
- [x] No allocation for small case #285 #301 
- [x] .zip_mut_with improvement reduces binary operation custom stride case overhead for ixdyn #292 
- [x] Fancier slicing, selecting subviews #215
